src/checker/checker/urls.py
from django.conf.urls import url
from django.contrib import admin
from creocheck import views
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, {}, "index"),
    url(r'^checks_admin/$', views.checks_admin, {}, "checks_admin"),
    url(r'^checks_admin_filter/(?P<active_assignment>\d+)$', views.checks_admin_filter, {}, "checks_admin_filter"),
    url(r'^checks_admin/check/(?P<pk>\d+)$', views.admin_check_detail, {}, "admin_check_detail"),
    url(r'^checks_admin/user/(?P<pk>\d+)$', views.admin_user_detail, {}, "admin_user_detail"),
    url(r'^checks_admin/excel_export/', views.admin_excel_export, {}, "admin_excel_export"),
    url(r'^receive-file$', views.receive_file, {}, "receive_file"),
    url(r'^update_tasks/$', views.update_tasks, {}, "update_tasks"),
    url(r'^task/(?P<pk>\d+)$', views.task_detail, {}, "index"),
    url(r'^login/$', views.activate_user_collection, {}, "activate_user_collection"),
    url(r'^logout/$', views.logout, {}, "logout"),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
]

src/checker/creocheck/models.py
from django.db import models

import traceback
from django.conf import settings


class UploadFile(models.Model):
    display_name = models.CharField(max_length=150, blank=True, null=True)
    file = models.FileField(upload_to='files')
    metadata = models.TextField(blank=True, null=True)

    def fileLink(self):
        if self.file:
            return '<a href="' + str(self.File.url) + '">' + 'NameOfFileGoesHere' + '</a>'
        else:
            return '<a href="''"></a>'

    fileLink.allow_tags = True
    fileLink.short_description = "File Link"

    def __str__(self):
        return "{} - {}".format(self.pk, self.file.name)


class MacroTemplate(models.Model):
    name = models.CharField(max_length=50)
    macro = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{} - {}".format(self.pk, self.name)







class AssignmentCollection(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return "{}".format(self.name)



class Assignment(models.Model):

    order = models.SmallIntegerField(default=0)

    collection = models.ForeignKey(AssignmentCollection)

    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    correct_file = models.FileField(upload_to='files')

    def __str__(self):
        return "{} - {}".format(self.pk, self.name)


    class Meta:
        ordering = ['order']


class CheckTemplate(models.Model):
    assignment = models.ForeignKey(Assignment)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    CHECK_FUNCS = (
            ('MassPropChecker', 'MassPropChecker'),
            ('ModelTreeChecker', 'ModelTreeChecker'),
            ('RegenChecker', 'RegenChecker'),
            ('MacroRunner', 'MacroRunner'),
            ('SaveMetadata', 'SaveMetadata'),
            ('SleepOneSecond', 'SleepOneSecond'),
            )

    check_func = models.CharField(max_length=50, choices=CHECK_FUNCS)

    # check parameters as JSON
    checkparams = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{} - {}".format(self.pk, self.name)


from django.contrib.auth.models import User

from creocheck.tasks import run_checktask


class CheckUser(models.Model):

    user_id = models.CharField(max_length=30)


    @property
    def passed(self):
        return CheckTask.objects.filter(user=self, passed=True).exists()


    @property
    def attempts(self):
        return CheckTask.objects.filter(user=self).count()



    def __str__(self):
        return "{}".format(self.user_id)


class CheckTask(models.Model):

    created = models.DateTimeField(auto_now_add=True, null=True)

    user = models.ForeignKey(CheckUser, null=True, blank=True)

    assignment = models.ForeignKey(Assignment)
    file = models.ForeignKey(UploadFile)

    progress = models.FloatField(default=0)
    done = models.BooleanField(default=False)
    error = models.BooleanField(default=False)
    passed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']

    def run(self):
        run_checktask.delay(self.pk)

    def set_progress(self, progress, max_progress):
        self.progress = float(progress) / float(max_progress)
        if progress == max_progress:
            self.done = True
        self.save()

    def get_checks(self):
        return Check.objects.filter(task=self)

    def get_status(self):

        if self.error:
            return "ERROR"

        if self.done:
            return "DONE"

        if self.progress == 0:
            return "PENDING"

        if self.progress > 0:
            return "IN PROGRESS"

    def __str__(self):
        return "{}".format(self.pk)


    class Meta:
        ordering = ['-passed', '-created']


class Check(models.Model):
    template = models.ForeignKey(CheckTemplate)
    task = models.ForeignKey(CheckTask)
    status = models.TextField(blank=True, null=True)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.template.check_func)


class CheckLogEvent(models.Model):

    check_object = models.ForeignKey(Check)
    created = models.DateTimeField(auto_now_add=True, null=True)
    text = models.CharField(max_length=300)

    def __str__(self):
        return "{} - {}: {}".format(self.created, self.check_object.template.name, self.text)

src/checker/creocheck/forms.py
from django import forms

from creocheck.models import UploadFile


class UploadFileForm(forms.ModelForm):

    class Meta:
        model = UploadFile
        fields = ('file',)

src/checker/creocheck/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest

# Create your views here.

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.core.files import File
from creocheck.forms import UploadFileForm
from creocheck.models import CheckTemplate, Assignment, CheckTask, CheckUser, AssignmentCollection, UploadFile
from django.http import HttpResponseRedirect
import io
import json
import random
import json
from django.conf import settings

from openpyxl import Workbook
from openpyxl.writer.excel import save_virtual_workbook
import io

from django.contrib.auth.decorators import login_required

import datetime


def get_user(request):
    return CheckUser.objects.get(pk=request.session.get('active_user_pk'))


def serialize_task(checktask):
    d = [
        checktask.pk, checktask.assignment.name, checktask.file.display_name, checktask.progress,
        checktask.get_status(), checktask.passed, None
    ]
    return d
    return json.dumps(d)


@login_required
def checks_admin(request):

    print(request.session.get("active_assignment"))
    try:
        selected_assignment = Assignment.objects.get(pk=request.session.get("active_assignment"))
        tasks = CheckTask.objects.filter(assignment=selected_assignment).order_by("-passed", "-created")
    except:
        tasks = CheckTask.objects.all().order_by("-passed", "-created")
    context = {}
    context.update({"tasks": tasks})
    return render(request, "creocheck/admin-main.html", context)


@login_required
def admin_check_detail(request, pk):
    checktask = CheckTask.objects.get(pk=pk)
    context = {}
    context.update({"checktask": checktask})
    return render(request, "creocheck/admin-check.html", context)


@login_required
def checks_admin_filter(request, active_assignment):
    request.session['active_assignment'] = active_assignment
    return HttpResponseRedirect("/checks_admin/")


@login_required
@csrf_exempt
def admin_excel_export(request):

    try:
        selected_assignment = Assignment.objects.get(pk=request.session.get("active_assignment"))
        tasks = CheckTask.objects.filter(assignment=selected_assignment).order_by("-passed", "-created")
    except:
        tasks = CheckTask.objects.all().order_by("-passed", "-created")

    print("EXPORT to EXCEL")
    header = ["Check ID", "User ID", "Timestamp", "Assignment", "Collection", "Passed"]

    wb = Workbook()
    ws = wb.active
    ws.append(header)
    for t in tasks:
        ws.append([t.pk, str(t.user), str(t.created), t.assignment.name, t.assignment.collection.name, str(t.passed)])
    out = io.BytesIO()
    wb.save(out)

    date_str = (datetime.datetime.now().strftime("CADVER_%y%m%d_%H%M%S"))
    response = HttpResponse(save_virtual_workbook(wb), content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename={}.xlsx'.format(date_str)
    return response


@login_required
def admin_user_detail(request, pk):
    user = CheckUser.objects.get(pk=pk)
    context = {}
    context.update({"user": user})
    return render(request, "creocheck/admin-user.html", context)


def update_tasks(request):
    checktasks = CheckTask.objects.filter(user=get_user(request)).order_by("-pk")[:6]
    l = {"data": [serialize_task(i) for i in checktasks]}
    return HttpResponse(json.dumps(l), content_type="application/json")


def activate_user_collection(request):
    user_id = (request.GET.get("user_id"))

    if len(user_id) < 5 or len(user_id) > 7:
        return HttpResponseBadRequest("Invalid link")

    assignment_collection_name = (request.GET.get("ac_name"))

    request.session['active_user_pk'] = CheckUser.objects.get_or_create(user_id=user_id)[0].pk
    try:
        request.session['active_collection_pk'] = AssignmentCollection.objects.get(name=assignment_collection_name).pk
    except AssignmentCollection.DoesNotExist:
        return HttpResponseBadRequest("Assignment collection does not exist")

    return HttpResponseRedirect("/")


from django.contrib.auth import logout as django_logout


def logout(request):
    request.session['active_user_pk'] = None
    django_logout(request)
    return HttpResponseRedirect("/")


def index(request):
    pk = request.session.get('active_user_pk')
    if not pk:
        return HttpResponse("USE LINK TO ACTIVATE SESSION.")
    if not CheckUser.objects.filter(pk=pk).exists():
        return HttpResponse("USE LINK TO ACTIVATE SESSION.")

    context = {}
    try:
        collection = AssignmentCollection.objects.get(pk=request.session.get('active_collection_pk'))
    except:
        return HttpResponse("USE LINK TO ACTIVATE SESSION.")

    context.update({'assignments': Assignment.objects.filter(collection=collection)})
    context.update({'refresh_rate': settings.REFRESH_RATE})
    context.update({'admin_email': settings.ADMIN_EMAIL})
    return render(request, "creocheck/index.html", context)


def task_detail(request, pk):
    task = CheckTask.objects.get(pk=pk, user=get_user(request))
    context = {}
    context.update({"task": task})
    context.update({"checks": task.get_checks()})
    return render(request, "creocheck/task-detail.html", context)


import uuid


@csrf_exempt
def receive_file(request):

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES['file']
            extension = f.name.split(".")[1].lower()
            display_name = f.name

            if not any(ext in extension for ext in settings.ALLOWED_EXTENSIONS):
                return HttpResponseBadRequest("INVALID FILE FORMAT")

            # generate the file a random name
            f.name = "{}.{}".format(str(uuid.uuid4()).split("-")[0], extension)
            # print(request.POST.get("assignment_name"))
            assignment = Assignment.objects.get(name=request.POST.get("assignment_name"))

            new_file = UploadFile(file=f, display_name=display_name)
            new_file.save()

            a = CheckTask.objects.create(assignment=assignment, file=new_file, user=get_user(request))
            print("Created checktask")
            print(CheckTask.objects.all().count())
            print("running checktask")
            a.run()
            return HttpResponse("OK")

    return HttpResponseBadRequest("Invalid request")

src/checker/creocheck/templates/creocheck/admin-base.html
<!DOCTYPE html>
<html lang="en">

  <head>

      {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CADVER Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">



    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 54px;
        padding: 45px 0 0 0;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }
    </style>

  </head>

  <body>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
              <a class="navbar-brand" href="{% url "checks_admin" %}">CADVER Admin</a>
              <ul class="nav navbar-nav mr-auto">
                  <li class="nav-item">
                      <a href="{% url "checks_admin_filter" 0 %}" class="nav-link">All</a>
                  </li>
                  {% for collection in assignment_collections %}
                  <li class="nav-item dropdown">
                      <a href="#" class="dropdown-toggle nav-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ collection }}</a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">

                  {% for assignment in collection.assignment_set.all %}
                  <a class="dropdown-item" href="{% url "checks_admin_filter" assignment.pk %}" class="nav-link">{{ assignment }}</a>
                  {% endfor %}
                      </div>
                  </li>
                  {% endfor %}
              </ul>
              <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item">
                      <a href="/admin" class="nav-link">Django admin</a>
                  </li>
                  <li class="nav-item">
                      <a href="{% url "logout" %}" class="nav-link">Log out</a>
                  </li>
              </ul>

          </div>
      </nav>

      {% block body %}
      {% endblock %}
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

src/checker/creocheck/templates/creocheck/admin-check.html
{% extends 'creocheck/admin-base.html' %}
{% block body %}



    <!-- Page Content -->
    <div class="container">
      <div class="row pt-3">
          <div class="col-lg-12">
              <h1>Details for checktask {{ checktask }}</h1>
              <h4>User: {{ checktask.user }}</h4>
              <h4>Passed: {{ checktask.passed }}</h4>
              <h4>Timestamp: {{ checktask.created | date:"d.m.y H:i:s"}}</h4>
              <h4>Uploaded file:  <a href="{{ checktask.file.file.url }}">{{ checktask.file.display_name }}</a></h4>

              <hr>


              <h4>Assignment: {{ checktask.assignment }}</h4>
              <h4>Correct file:  <a href="{{ checktask.assignment.correct_file.file.url }}">{{ checktask.assignment.correct_file }}</a></h4>

              <hr>
              <h2>Check details</h2>
              <table class="table" id="task-table">
                  <thead>
                      <tr>
                          <th>Check template name</th>
                          <th>Check function</th>
                          <th>Description</th>
                          <th>Info</th>
                          <th>Passed</th>
                          <th>Check log</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for check in checktask.check_set.all %}
                      <tr>
                          <th><small>{{ check.template.name }}</small></th>
                          <th><small>{{ check.template.check_func }}</small></th>
                          <th><small>{{ check.template.description }}</small></th>
                          <th><small>{{ check.status }}</small></th>
                          <th><small>{{ check.passed }}</small></th>
                          <th style="white-space:nowrap;">
                              <small>
                                  {% for i in check.checklogevent_set.all %}
                                  {{ i }}<br>
                                  {% endfor %}
                              </small>
                          </th>



                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
      <hr>

    </div>

{% endblock %}

src/checker/creocheck/templates/creocheck/admin-main.html
{% extends 'creocheck/admin-base.html' %}
{% block body %}

    <!-- Page Content -->
    <div class="container">
      <div class="row pt-3">
          <div class="col-lg-12">
              <a role="button" class="btn btn-primary" href="{% url "admin_excel_export"%}">Export current</a>
          </div>
      </div>
      <hr>

      <div class="row pt-2">
        <div class="col-lg-12">

            <table class="table">
                <thead>
                    <tr>
                        <th>CheckTask ID</th>
                        <th>User ID</th>
                        <th>Timestamp</th>
                        <th>Assignment</th>
                        <th>Passed</th>
                        <th>File</th>
                    </tr>
                </thead>
                <tbody>

                {% for c in tasks %}
                    <tr id="{{c.pk}}">
                        <td><a href="{% url "admin_check_detail" c.pk %}">{{c.pk}}</a></td>
                        <td><a href="{% url "admin_user_detail" c.user.pk %}">{{c.user}}</a></td>
                        <td>{{ c.created | date:"d.m.y H:i:s"}}</td>
                        <td>{{ c.assignment.name }}</td>
                        <td>{{ c.passed  }}</td>
                        <td> <a href="{{ c.file.file.url }}">{{ c.file.display_name }}</a><td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>


          <!--<h1 class="mt-5">A Bootstrap 4 Starter Template</h1>-->
          <!--<p class="lead">Complete with pre-defined file paths and responsive navigation!</p>-->
          <!--<ul class="list-unstyled">-->
            <!--<li>Bootstrap 4.0.0-beta</li>-->
            <!--<li>jQuery 3.2.1</li>-->
          <!--</ul>-->
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->

{% endblock %}

src/checker/creocheck/templates/creocheck/admin-user.html
{% extends 'creocheck/admin-base.html' %}
{% block body %}



    <!-- Page Content -->
    <div class="container">
      <div class="row pt-3">
          <div class="col-lg-12">
              <h1>Details for user {{ user }}</h1>
              <hr>

              <h2>Checks</h2>

              <table class="table">
                  <thead>
                      <tr>
                          <th>Check ID</th>
                          <th>Timestamp</th>
                          <th>Assignment</th>
                          <th>Assignment collection</th>
                          <th>Passed</th>
                          <th>File</th>
                      </tr>
                  </thead>
                  <tbody>

                      {% for c in user.checktask_set.all %}
                      <tr id="{{c.pk}}">
                          <td><a href="{% url "admin_check_detail" c.pk %}">{{c.pk}}</a></td>
                          <td>{{ c.created | date:"d.m.y H:i:s"}}</td>
                          <td>{{ c.assignment.name }}</td>
                          <td>{{ c.assignment.collection.name }}</td>
                          <td>{{ c.passed  }}</td>
                          <td> <a href="{{ c.file.file.url }}">{{ c.file.display_name }}</a><td>
                      </tr>
                      {% endfor %}

                  </tbody>
              </table>



    </div>
    </div>
    </div>

{% endblock %}

src/checker/creocheck/templates/creocheck/base.html
<!DOCTYPE html>

<meta charset="utf-8">

<title>CADVER</title>
{% load static %}

<html lang="en">
    <head>
        <script src="https://use.fontawesome.com/b26e0746db.js"></script>
        <meta charset="utf-8">
        <meta name="description" content="CAD file checker">
        <title>CADVER</title>
        <link rel="stylesheet" href="{% static "sakura.css" %}" type="text/css">
        <link rel="stylesheet" href="{% static "dropzone.css" %}">
        <script src="{% static "jquery-3.2.1.min.js" %}"></script>
        <script src="{% static "dropzone.js" %}"></script>
        <script src="{% static "progressbar.js" %}"></script>
        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>

    </head>


    <body>
        {% block body %}
        {% endblock %}
    </body>

</html>

src/checker/creocheck/templates/creocheck/checks-admin.html
{% extends 'creocheck/base.html' %}
{% block body %}


<header>
    <h1>Admin</h1>
</header>

<div class="topnav">
    Assignment collection:
  <a class="active" href="#home">Home</a>
</div>

<div class="topnav">
  Assignment:
  <a class="active" href="#home">All</a>
  <a class="active" href="#home">Home</a>
</div>


<button type="button">CSV export</button>

<hr>
<table id="task-table">
    <thead>
        <tr>
            <th>User ID</th>
            <th>Attempts</th>
            <th>Check details</th>
        </tr>
    </thead>
    <tbody>
        {% for u in users %}
        <tr>
            <th>{{ u.user_id }}</th>
            <th>{{ u.checktask_set.count }}</th>
            <th>
                <table>
                {% for t in u.checktask_set.all %}
                <small>
                    <th width="500px" >
                    {{ t.assignment.name }}<br>
                    {{ t.created | date:"d.m.Y H:m:s"}}<br>
                    ID: {{ t.pk }}<br>
                    <a href="{{ t.file.file.url }}">{{ t.file.display_name }}</a><br>
                    Passed: {{ t.passed }}<br>
                    Following checks were run: <br>
                    {% for check in t.check_set.all %}
                    {{ check }}: {{ check.passed }}<br>
                    {% endfor %}
                    </th>
                </small>
                {% endfor %}
                </table>
            </th>



        </tr>
        {% endfor %}
    </tbody>
</table>



<style>

div.half {
    width: 20%;
    margin: auto;
        #border: 3px solid #73AD21;
}

tr.active {
    background: #b8d1f3;
}
</style>

{% endblock %}

src/checker/creocheck/templates/creocheck/index.html
{% extends 'creocheck/base.html' %}
{% block body %}
{% if active_user %} <small>Logged in as {{ active_user }} - <a href="{% url "logout" %}">Log out</a></small>  <br>{% endif %}
<small>For support, please contact <a href="mailto:{{ admin_email }}">{{ admin_email }}</a></small>
<header>
    <h2>CADVER</h2>
    <h3>CAD Exercise Assessment System</h3>
</header>



    <p><label for="select">Select assignment</label> <select id="assignment">
        {% for a in assignments %}
        <option id="{{ a.pk }}" >
            {{ a.name }}
        </option>
        {% endfor %}
    </select></p>



<form action="{% url "receive_file" %}" class="dropzone" id="dropzoneJsForm"></form>
<br>
<br>
<hr>
<br>

<table id="task-table">
    <thead>
        <tr>
            <th>Task</th>
            <th>Assignment</th>
            <th>File</th>
            <th>Progress</th>
            <th>Task status</th>
            <th>Passed</th>
            <th></th>
        </tr>
    </thead>
</table>



<style>

div.half {
    width: 20%;
    margin: auto;
        #border: 3px solid #73AD21;
}

tr.active {
    background: #b8d1f3;
}
</style>


<script>

Dropzone.autoDiscover = false;

    $(document).ready(function() {

        //preserve the selection in localstorage
        $('#assignment').on('change', function() {
            localStorage.setItem("selected_assignment", $(this).val());
        });

        // if localstorage val does not exist, default to the first

        if ($('#assignment').length) {
            $('#assignment').val(localStorage.getItem("selected_assignment"));
            if ($('#assignment').val() == null) {
                $("#assignment").val($("#assignment option:first").val());
            }
        }


        var table = $('#task-table').DataTable( {
            "ajax": '{% url "update_tasks" %}',
            "dom": "tr",
            "bSort" : false,
            "fnCreatedRow" : function (row, data, dataIndex) {
                var id = $("td:eq(0)", row).text();


                tick = "<i style='color:green' class='fa fa-check' aria-hidden='true'></i>";
                cross = "<i style='color:red' class='fa fa-times' aria-hidden='true'></i>";

                var passed= $("td:eq(5)", row);
                if (passed.text() == "true"){
                    passed.html(tick);
                }
                else if ($("td:eq(4)", row).text() == "PENDING") {
                    passed.html("");
                }
                else {
                    passed.html(cross);
                }

                var open = $("td:eq(6)", row);
                open.html('<button type="button">Details</button>');




                var cell = $("td:eq(3)", row);
                var progress = parseFloat($("td:eq(3)", row).text());
                var div = document.createElement("div");
                cell.html("<div class='barcontainer' id='bar" + id + "'></div>");
                console.log(progress)
                cell.data();
                table.draw();
                bar = new ProgressBar.Line("#bar" + id, {
                    strokeWidth: 5,
                    easing: 'easeInOut',
                    duration: 500,
                    color: '#226b77',
                    trailColor: '#eee',
                    trailWidth: 1,
                    svgStyle: null,
                    step: (state, bar) => {
                        bar.setText(Math.round(bar.value() * 100) + ' %');
                    },
                    text: {
                        style: {
                            color: '#999',
                            position: 'center',
                            right: '0',
                            top: '20px',
                            padding: 0,
                            margin: 0,
                            transform: null
                        },
                    }

                });
                bar.set(progress);


            },

        });
        var bar;

        $('#task-table').on( 'click', 'tr', function () {
            var id = $("td:eq(0)", this).text();
            if (id) location.href = "task/" + id;
            });






        function update_tasks(){
            table.ajax.reload( function(json){
            });

            <!--bar.animate(0.7);-->

        }

        var delay = {{ refresh_rate }};

        setInterval(update_tasks, delay);


        //DROP ZONE
        var md = new Dropzone(".dropzone", {
            url: "{% url "receive_file" %}",

            init: function() {
            this.on("sending", function(file, xhr, formData){
                formData.append("assignment_name", $("#assignment").val() );
            });
            },


            maxFilesize: "50",
            addRemoveLinks: false,
        });

        md.on("complete", function (file) {
            if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
                setTimeout(function(){
                    //location.reload();
                }, 1000);
            }
        });


    });



</script>

{% endblock %}

src/checker/creocheck/templates/creocheck/task-detail.html
{% extends 'creocheck/base.html' %}
{% block body %}


<a href="/">
    Back
</a>
<header>
    <h1>Check for {{ task.assignment.name }}</h1>
</header>

<p>
Submitted file: {{ task.file.display_name }}
</p>
<p>
Comparing to file: {{ task.assignment.correct_file.name }}
</p>

<hr>
<table id="task-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Check function</th>
            <th>Description</th>
            <!--<th>Info</th>-->
            <th>Passed</th>
            <th>Check log</th>
        </tr>
    </thead>
    <tbody>
        {% for check in checks %}
        <tr>
            <th><small>{{ check.template.name }}</small></th>
            <th><small>{{ check.template.check_func }}</small></th>
            <th><small>{{ check.template.description }}</small></th>
            <!--<th>{{ check.status }}</th>-->
            {% if check.passed %}
            <th><i style='color:green' class='fa fa-check' aria-hidden='true'></i></th>
            {% else %}
            <th><center><i style='color:red' class='fa fa-times' aria-hidden='true'></i></center></th>
            {% endif %}
            <th style="white-space:nowrap;">
                <small>
                    {% for i in check.checklogevent_set.all %}
                    {{ i }}<br>
                    {% endfor %}
                </small>
            </th>



        </tr>
        {% endfor %}
    </tbody>
</table>



<style>

div.half {
    width: 20%;
    margin: auto;
        #border: 3px solid #73AD21;
}

tr.active {
    background: #b8d1f3;
}
</style>

{% endblock %}